-- Sample data for customers table
-- This file is automatically executed by Spring Boot on startup

INSERT INTO customers (name, email, phone, created_at) VALUES 
('John Doe', 'john.doe@example.com', '+1-555-0101', CURRENT_TIMESTAMP),
('Jane Smith', 'jane.smith@example.com', '+1-555-0102', CURRENT_TIMESTAMP),
('Robert Johnson', 'robert.johnson@example.com', '+1-555-0103', CURRENT_TIMESTAMP),
('Emily Davis', 'emily.davis@example.com', '+1-555-0104', CURRENT_TIMESTAMP),
('Michael Wilson', 'michael.wilson@example.com', '+1-555-0105', CURRENT_TIMESTAMP),
('Sarah Brown', 'sarah.brown@example.com', '+1-555-0106', CURRENT_TIMESTAMP),
('David Lee', 'david.lee@example.com', '+1-555-0107', CURRENT_TIMESTAMP),
('Jennifer Taylor', 'jennifer.taylor@example.com', '+1-555-0108', CURRENT_TIMESTAMP),
('James Anderson', 'james.anderson@example.com', '+1-555-0109', CURRENT_TIMESTAMP),
('Lisa Martinez', 'lisa.martinez@example.com', '+1-555-0110', CURRENT_TIMESTAMP),
('Christopher Garcia', 'christopher.garcia@example.com', '+1-555-0111', CURRENT_TIMESTAMP),
('Amanda Rodriguez', 'amanda.rodriguez@example.com', '+1-555-0112', CURRENT_TIMESTAMP),
('Daniel White', 'daniel.white@example.com', '+1-555-0113', CURRENT_TIMESTAMP),
('Jessica Lopez', 'jessica.lopez@example.com', '+1-555-0114', CURRENT_TIMESTAMP),
('Matthew Hill', 'matthew.hill@example.com', '+1-555-0115', CURRENT_TIMESTAMP),
('Ashley Moore', 'ashley.moore@example.com', '+1-555-0116', CURRENT_TIMESTAMP),
('Andrew Taylor', 'andrew.taylor@example.com', '+1-555-0117', CURRENT_TIMESTAMP),
('Stephanie Green', 'stephanie.green@example.com', '+1-555-0118', CURRENT_TIMESTAMP),
('Joshua Adams', 'joshua.adams@example.com', '+1-555-0119', CURRENT_TIMESTAMP),
('Nicole Baker', 'nicole.baker@example.com', '+1-555-0120', CURRENT_TIMESTAMP),
('Brandon Gonzalez', 'brandon.gonzalez@example.com', '+1-555-0121', CURRENT_TIMESTAMP),
('Melissa Nelson', 'melissa.nelson@example.com', '+1-555-0122', CURRENT_TIMESTAMP),
('Kevin Carter', 'kevin.carter@example.com', '+1-555-0123', CURRENT_TIMESTAMP),
('Rebecca Mitchell', 'rebecca.mitchell@example.com', '+1-555-0124', CURRENT_TIMESTAMP),
('Brian Phillips', 'brian.phillips@example.com', '+1-555-0125', CURRENT_TIMESTAMP),
('Michelle Edwards', 'michelle.edwards@example.com', '+1-555-0126', CURRENT_TIMESTAMP),
('Jason Collins', 'jason.collins@example.com', '+1-555-0127', CURRENT_TIMESTAMP),
('Laura Stewart', 'laura.stewart@example.com', '+1-555-0128', CURRENT_TIMESTAMP),
('Justin Sanchez', 'justin.sanchez@example.com', '+1-555-0129', CURRENT_TIMESTAMP),
('Kimberly Morris', 'kimberly.morris@example.com', '+1-555-0130', CURRENT_TIMESTAMP);
